### PR TITLE
输入演员链接，下载所有该演员相关的影片

### PR DESCRIPTION
**Pull request by zydmayday**
image

### CODE REVIEW

**Comment by Dissyu** [comment]
只能下載第一頁的24部影片，第二頁的無法下載........

**Comment by zydmayday** [comment]
@Dissyu 
是的，網站的頁面切換是用的JS進行的處理，所以不好控制。
不過對於大多數不超過24部影片的頁面，還是很好用的。

**Comment by zydmayday** [comment]
可以通过下述的url来查找下一页的视频。
https://jable.tv/models/shinoda-yuu/?from=01
https://jable.tv/models/shinoda-yuu/?from=02
这样就可以查到之后页面的内容了。

**Comment by zydmayday** [comment]
如果想要按照观影次数排序：https://jable.tv/models/shinoda-yuu/?from=02&sort_by=video_viewed

**Comment by 2niuhe** [comment]
@Dissyu 

需要下载多页的，可以看看这个  https://github.com/2niuhe/jable_downloader

**Comment by Dissyu** [comment]
> @Dissyu
> 
> 需要下载多页的，可以看看这个 https://github.com/2niuhe/jable_downloader

感謝，我測試了一下，發現下載非常慢，會常常卡一下，五分鐘後左右又繼續下載哪種

不知道大大有遇到嗎

**Comment by cy920820** [comment]
@zydmayday <Response [403]> 这个是什么鬼？

**Comment by zydmayday** [comment]
@cy920820 
我试了一下，如果是命令行比如


```bash
curl https://jable.tv/models/yua-mikami/
```

会返回下面的信息。

> This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.

大概意思就是这个网站加强了安全性能，不能直接抓取数据了。

**Comment by zydmayday** [comment]
我试了一种别的方法，修改在https://github.com/hcjohn463/JableTVDownload/pull/78/commits/44dcab7dee65d46d7821b6720bac0b85671134fc

操作步骤
1. pip install -r requirements.txt
2. python main.py --all-urls {女优主页链接}

**注意！！！**
我用的selenium做为代替方案，坏处是执行python的时候会弹出jable.tv的窗口（Chrome），
如果周围有人或者公众场合请不要使用！lol

**Comment by Dissyu** [comment]
> 

感謝~~ 晚上回家試試看~

**Comment by Dissyu** [comment]
> 我试了一种别的方法，修改在[44dcab7](https://github.com/hcjohn463/JableTVDownload/commit/44dcab7dee65d46d7821b6720bac0b85671134fc)
> 
> 操作步骤
> 
> 1. pull 最新的代码
> 2. pip install -r requirements.txt
> 3. python main.py --all-urls {女优主页链接}
> 
> **注意！！！** 我用的selenium做为代替方案，坏处是执行python的时候会弹出jable.tv的窗口（Chrome）， 如果周围有人或者公众场合请不要使用！lol （不过只要你不尴尬，尴尬的就是别人）

image

我在ubuntu遇到了這樣的問題 ........  是有哪裡做錯嗎，謝謝

**Comment by zydmayday** [comment]
@Dissyu 
selenium会打开chrome，如果你有ubuntu你有安装chrome吗，我用的windows不太确定。

**Comment by cy920820** [comment]
> @cy920820 我试了一下，如果是命令行比如
> 
> ```shell
> curl https://jable.tv/models/yua-mikami/
> ```
> 
> 会返回下面的信息。
> 
> > This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.
> > Enable JavaScript and cookies to continue
> 
> ~大概意思就是这个网站加强了安全性能，不能直接抓取数据了。~ 我想应该是我们要enable JavaScript和Cookie，这样我们就可以正常抓取了

刚拉的你最新的 main 分之，报错了：

python main.py --all-urls https://jable.tv/models/yua-mikami/


Traceback (most recent call last):
  File "/Users/cy920820/cy920820/JableTVDownload-multi/main.py", line 34, in <module>
    urls = movieLinks(all_urls)
  File "/Users/cy920820/cy920820/JableTVDownload-multi/movies.py", line 10, in movieLinks
    dr = webdriver.Chrome()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/jable/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
    super().__init__(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/jable/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/jable/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/jable/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/jable/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/jable/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 108
Current browser version is 112.0.5615.49 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Stacktrace:
0   chromedriver                        0x0000000102d77b7c chromedriver + 4209532
1   chromedriver                        0x0000000102d03418 chromedriver + 3732504
2   chromedriver                        0x00000001029b6368 chromedriver + 271208
3   chromedriver                        0x00000001029e12fc chromedriver + 447228
4   chromedriver                        0x00000001029dd098 chromedriver + 430232
5   chromedriver                        0x00000001029da1c4 chromedriver + 418244
6   chromedriver                        0x0000000102a1a33c chromedriver + 680764
7   chromedriver                        0x0000000102a19d94 chromedriver + 679316
8   chromedriver                        0x00000001029e459c chromedriver + 460188
9   chromedriver                        0x00000001029e5644 chromedriver + 464452
10  chromedriver                        0x0000000102d4930c chromedriver + 4018956
11  chromedriver                        0x0000000102d4cfd8 chromedriver + 4034520
12  chromedriver                        0x0000000102d5311c chromedriver + 4059420
13  chromedriver                        0x0000000102d4dbac chromedriver + 4037548
14  chromedriver                        0x0000000102d27bb0 chromedriver + 3881904
15  chromedriver                        0x0000000102d6a120 chromedriver + 4153632
16  chromedriver                        0x0000000102d6a274 chromedriver + 4153972
17  chromedriver                        0x0000000102d7e82c chromedriver + 4237356
18  libsystem_pthread.dylib             0x000000019ceaffa8 _pthread_start + 148
19  libsystem_pthread.dylib             0x000000019ceaada0 thread_start + 8

**Comment by Dissyu** [comment]
> @Dissyu selenium会打开chrome，如果你用ubuntu你有安装chrome吗，我用的windows所以不太确定ubuntu的情况。



> @Dissyu selenium会打开chrome，如果你用ubuntu你有安装chrome吗，我用的windows所以不太确定ubuntu的情况。

有沒有辦法幫忙修改一份版本是firefox瀏覽器，因為chrome在ubuntu比較不好弄 .... 我是用樹梅派AMR64

**Comment by zydmayday** [comment]
@cy920820 
hmm，你用的mac，这个我也没设备暂时没法测，我还在工作，晚点看看有没有办法解决

**Comment by zydmayday** [comment]
@Dissyu @cy920820 
这个参数可以调整，
https://github.com/hcjohn463/JableTVDownload/blob/cebea0cbb4711c016aab9d51535c2b6ae6f7064a/movies.py#L10
你们可以试试别的driver

**Comment by cy920820** [comment]
> @Dissyu @cy920820 这个参数可以调整，
> 
> https://github.com/hcjohn463/JableTVDownload/blob/cebea0cbb4711c016aab9d51535c2b6ae6f7064a/movies.py#L10
> 
> 
> 你们可以试试别的driver

好的，好的 ，打扰了

**Comment by cy920820** [comment]
我试着改了 chromedriver 版本，可以了，但是我发现我没办法访问jable.tv，你们那边服务都挂了吗？还是我这边电脑的问题？？

**Comment by zydmayday** [comment]
@cy920820 我可以访问jable.tv，刚才试了可以

**Comment by Dissyu** [comment]
> @cy920820 我可以访问jable.tv，刚才试了可以

目前測試win10沒問題，ubuntu還要再研究，謝謝大哥迅速的修正，感激不盡!!!

**Comment by hcjohn463** [comment]
謝謝您的貢獻!

**Pull request merged**
